// Question bank: 20 questions per category, one category per day.
// Day mapping uses JavaScript Date.getDay(): 0=Sun, 1=Mon, ..., 6=Sat.

const CATEGORIES = {
  1: { name: "Monday — Math Word Problems", key: "math" },
  2: { name: "Tuesday — Geography",          key: "geography" },
  3: { name: "Wednesday — History",          key: "history" },
  4: { name: "Thursday — Physics",           key: "physics" },
  5: { name: "Friday — Chemistry",           key: "chemistry" },
  6: { name: "Saturday — Chess Puzzle",      key: "chess" },
  0: { name: "Sunday — Biology (Evolution)", key: "biology" },
};

const QUESTIONS = {
  math: [
    { q: "A train travels 120 miles in 2 hours. What is its average speed in mph?",
      a: "60 mph. Speed = distance ÷ time = 120 ÷ 2 = 60." },
    { q: "Sarah has 3 times as many apples as Tom. Together they have 24 apples. How many does Sarah have?",
      a: "18 apples. Let Tom have x; then Sarah has 3x. x + 3x = 24, so x = 6 and Sarah = 18." },
    { q: "A rectangle has a length of 12 cm and a width of 5 cm. What is its area?",
      a: "60 cm². Area = length × width = 12 × 5 = 60." },
    { q: "If 4 pencils cost $1.20, how much do 7 pencils cost at the same rate?",
      a: "$2.10. Each pencil costs 1.20 ÷ 4 = $0.30, so 7 × 0.30 = $2.10." },
    { q: "A shirt is on sale for 20% off its original price of $45. What is the sale price?",
      a: "$36. Discount = 0.20 × 45 = $9; sale price = 45 − 9 = $36." },
    { q: "Two cars leave the same point and drive in opposite directions, one at 50 mph and the other at 60 mph. How far apart are they after 3 hours?",
      a: "330 miles. They separate at (50 + 60) = 110 mph, so 110 × 3 = 330." },
    { q: "The sum of three consecutive integers is 72. What are they?",
      a: "23, 24, and 25. Let the middle integer be n; then 3n = 72, so n = 24." },
    { q: "A bag contains 5 red and 3 blue marbles. What is the probability of drawing a red marble at random?",
      a: "5/8. P(red) = number of red ÷ total = 5 ÷ 8." },
    { q: "Pipe A fills a tank in 4 hours and pipe B fills it in 6 hours. How long to fill together?",
      a: "2.4 hours (12/5 hours). Combined rate = 1/4 + 1/6 = 5/12 tanks/hour, so time = 12/5." },
    { q: "The angles of a triangle are in the ratio 2:3:4. Find the largest angle.",
      a: "80°. The parts sum to 9; each part = 180/9 = 20°. Largest = 4 × 20 = 80°." },
    { q: "A book costs $15 after a 25% discount. What was its original price?",
      a: "$20. $15 = 0.75 × original, so original = 15 / 0.75 = $20." },
    { q: "If x + y = 10 and x − y = 4, find x and y.",
      a: "x = 7, y = 3. Adding the two equations gives 2x = 14, so x = 7 and y = 3." },
    { q: "A car travels 240 miles on 8 gallons of gas. How many gallons are needed for 360 miles at the same rate?",
      a: "12 gallons. Mileage = 240/8 = 30 mpg, so 360 / 30 = 12 gallons." },
    { q: "A circular garden has a radius of 7 m. Find its area, using π = 22/7.",
      a: "154 m². Area = π r² = (22/7) × 49 = 154." },
    { q: "The average of 5 numbers is 20. If a sixth number is added and the new average is 22, what is the sixth number?",
      a: "32. Old sum = 100; new sum = 6 × 22 = 132; sixth number = 132 − 100 = 32." },
    { q: "A worker earns $15/hour for the first 40 hours and time-and-a-half (1.5×) after that. What does she earn for a 50-hour week?",
      a: "$825. Regular pay = 40 × 15 = $600; overtime = 10 × 22.50 = $225; total = $825." },
    { q: "A rectangular pool is 25 m long and 10 m wide. A 2 m wide path surrounds it. What is the area of just the path?",
      a: "156 m². Outer rectangle = 29 × 14 = 406; pool = 250; path = 406 − 250 = 156." },
    { q: "Pencils cost $0.50 each and pens cost $1.00 each. Sara buys 12 items for a total of $8.00. How many pens did she buy?",
      a: "4 pens (and 8 pencils). If p = pens, then p + (12 − p)·0.5 = 8 → 0.5p + 6 = 8 → p = 4." },
    { q: "A 150 m long train passes a stationary pole in 15 seconds. What is its speed in m/s?",
      a: "10 m/s. The train must cover its own length, so speed = 150 / 15 = 10 m/s." },
    { q: "A father is three times as old as his son. In 10 years, he will be twice as old as his son. How old is the son now?",
      a: "10 years old. Let son = s, father = 3s. Then 3s + 10 = 2(s + 10) → s = 10." },
  ],

  geography: [
    { q: "What is the longest river in the world?",
      a: "The Nile, at about 6,650 km (Amazon is a close second and is contested by some measurements)." },
    { q: "Which country has the largest land area?",
      a: "Russia, covering about 17.1 million km²." },
    { q: "What is the capital of Australia?",
      a: "Canberra (not Sydney). It was chosen as a compromise between Sydney and Melbourne." },
    { q: "Mount Everest lies on the border of which two countries?",
      a: "Nepal and China (Tibet Autonomous Region)." },
    { q: "What is the smallest country in the world by area?",
      a: "Vatican City, about 0.49 km²." },
    { q: "Which is the largest desert in the world?",
      a: "Antarctica. Polar deserts count as deserts (low precipitation); it is larger than the Sahara." },
    { q: "The Amazon rainforest is located primarily in which country?",
      a: "Brazil, which contains roughly 60% of the rainforest." },
    { q: "What is the largest ocean on Earth?",
      a: "The Pacific Ocean, covering about a third of Earth's surface." },
    { q: "Which African country has the most pyramids?",
      a: "Sudan. It contains more pyramids (about 200+ Nubian pyramids) than Egypt." },
    { q: "The Great Barrier Reef is off the coast of which country?",
      a: "Australia (off the northeast coast of Queensland)." },
    { q: "What is the capital of Canada?",
      a: "Ottawa, in the province of Ontario." },
    { q: "Through how many countries does the Equator pass?",
      a: "13 countries: Ecuador, Colombia, Brazil, São Tomé and Príncipe, Gabon, Republic of the Congo, DR Congo, Uganda, Kenya, Somalia, Maldives, Indonesia, Kiribati." },
    { q: "Which mountain range is traditionally considered the boundary between Europe and Asia?",
      a: "The Ural Mountains in Russia." },
    { q: "What is the deepest known oceanic trench?",
      a: "The Mariana Trench in the western Pacific, with the Challenger Deep at about 11,000 m." },
    { q: "What is the largest island in the world (excluding continents)?",
      a: "Greenland." },
    { q: "What is the official language of Brazil?",
      a: "Portuguese." },
    { q: "Which body of water is the saltiest commonly known sea?",
      a: "The Dead Sea (technically a salt lake), with about 34% salinity." },
    { q: "Lake Baikal, the world's deepest freshwater lake, is in which country?",
      a: "Russia (southern Siberia)." },
    { q: "What narrow strait separates Asia and North America?",
      a: "The Bering Strait, between Russia and Alaska." },
    { q: "Which transcontinental country lies in both Europe and Asia and has Istanbul as its largest city?",
      a: "Turkey." },
  ],

  history: [
    { q: "In what year did World War II end?",
      a: "1945. V-E Day was May 8 and Japan formally surrendered on September 2, 1945." },
    { q: "Who was the first President of the United States?",
      a: "George Washington, in office from 1789 to 1797." },
    { q: "In what year did the Berlin Wall fall?",
      a: "1989, on November 9." },
    { q: "Who wrote The Communist Manifesto?",
      a: "Karl Marx and Friedrich Engels, published in 1848." },
    { q: "What ancient civilization built Machu Picchu?",
      a: "The Inca, in the 15th century in present-day Peru." },
    { q: "Who was the first emperor to unify China?",
      a: "Qin Shi Huang, in 221 BCE." },
    { q: "In what year did the French Revolution begin?",
      a: "1789, marked by the storming of the Bastille on July 14." },
    { q: "Who led the Soviet Union during World War II?",
      a: "Joseph Stalin." },
    { q: "In what year did Christopher Columbus first reach the Americas?",
      a: "1492." },
    { q: "Who is the longest-reigning British monarch?",
      a: "Queen Elizabeth II, who reigned for over 70 years (1952–2022), surpassing Queen Victoria." },
    { q: "In what year was the Magna Carta signed?",
      a: "1215, by King John of England at Runnymede." },
    { q: "Who painted the ceiling of the Sistine Chapel?",
      a: "Michelangelo, between 1508 and 1512." },
    { q: "What war was fought in the United States from 1861 to 1865?",
      a: "The American Civil War." },
    { q: "Who was the first woman to win a Nobel Prize?",
      a: "Marie Curie, in Physics in 1903 (and later Chemistry in 1911)." },
    { q: "In what year did the Western Roman Empire traditionally fall?",
      a: "476 CE, when the emperor Romulus Augustulus was deposed." },
    { q: "Who invented the movable-type printing press in Europe?",
      a: "Johannes Gutenberg, around 1440." },
    { q: "Which empire did Genghis Khan found in the early 13th century?",
      a: "The Mongol Empire." },
    { q: "The Treaty of Versailles (1919) formally ended which war?",
      a: "World War I." },
    { q: "Who was the first person to walk on the Moon?",
      a: "Neil Armstrong, on July 20, 1969, during the Apollo 11 mission." },
    { q: "What was the name of the ship that brought the Pilgrims to North America in 1620?",
      a: "The Mayflower." },
  ],

  physics: [
    { q: "What is the speed of light in a vacuum (to a reasonable approximation)?",
      a: "About 3 × 10⁸ m/s (exactly 299,792,458 m/s)." },
    { q: "Who proposed the theory of general relativity?",
      a: "Albert Einstein, in 1915." },
    { q: "State Newton's second law of motion as a formula.",
      a: "F = m·a (force equals mass times acceleration)." },
    { q: "What is the SI unit of electric current?",
      a: "The ampere (A)." },
    { q: "Which subatomic particle in the nucleus has no electric charge?",
      a: "The neutron." },
    { q: "What is the approximate acceleration due to gravity at Earth's surface?",
      a: "About 9.81 m/s² (often rounded to 9.8 m/s²)." },
    { q: "What is the formula for kinetic energy?",
      a: "KE = ½·m·v²." },
    { q: "What does E = m·c² express?",
      a: "Mass-energy equivalence: energy and mass are interchangeable, related by the square of the speed of light." },
    { q: "What is the SI unit of frequency?",
      a: "The hertz (Hz), equal to one cycle per second." },
    { q: "What is the approximate wavelength range of visible light?",
      a: "About 400 to 700 nanometres (violet to red)." },
    { q: "What principle explains why objects float or sink in a fluid?",
      a: "Archimedes' principle: the buoyant force equals the weight of the fluid displaced." },
    { q: "What does the first law of thermodynamics state, in plain English?",
      a: "Energy is conserved: it cannot be created or destroyed, only transformed (ΔU = Q − W)." },
    { q: "What is the electric charge of an electron?",
      a: "Approximately −1.602 × 10⁻¹⁹ coulombs." },
    { q: "What instrument measures atmospheric pressure?",
      a: "A barometer." },
    { q: "A 2 kg object accelerates at 3 m/s². What net force acts on it?",
      a: "6 N. From F = m·a = 2 × 3 = 6 newtons." },
    { q: "Who formulated the law of universal gravitation?",
      a: "Isaac Newton, published in his Principia (1687)." },
    { q: "What is the SI unit of work and energy?",
      a: "The joule (J). One joule equals one newton-metre." },
    { q: "What is the Doppler effect?",
      a: "The change in observed frequency (or wavelength) of a wave caused by relative motion between source and observer." },
    { q: "What is the only natural satellite of Earth?",
      a: "The Moon." },
    { q: "A circuit has voltage V = 12 V and current I = 3 A. What is its resistance?",
      a: "4 Ω. From Ohm's law, R = V / I = 12 / 3 = 4." },
  ],

  chemistry: [
    { q: "What is the chemical symbol for gold?",
      a: "Au (from the Latin 'aurum')." },
    { q: "What is the most abundant gas in Earth's atmosphere?",
      a: "Nitrogen (N₂), about 78% by volume." },
    { q: "What is the pH of pure water at 25 °C?",
      a: "7 (neutral)." },
    { q: "What is the chemical formula for common table salt?",
      a: "NaCl (sodium chloride)." },
    { q: "How many protons does a carbon atom have?",
      a: "6. The atomic number of carbon is 6." },
    { q: "Which gas do plants take in for photosynthesis?",
      a: "Carbon dioxide (CO₂), and they release oxygen." },
    { q: "What is the lightest (least massive) element on the periodic table?",
      a: "Hydrogen (H), atomic number 1." },
    { q: "Which acid gives vinegar its sour taste?",
      a: "Acetic acid (CH₃COOH)." },
    { q: "What element has the chemical symbol Fe?",
      a: "Iron (from the Latin 'ferrum')." },
    { q: "What is the chemical formula for water?",
      a: "H₂O." },
    { q: "Who is often called the 'father of modern chemistry'?",
      a: "Antoine Lavoisier, for establishing the law of conservation of mass and modern naming conventions." },
    { q: "What is the most abundant element in the universe?",
      a: "Hydrogen, making up roughly three-quarters of all ordinary matter." },
    { q: "What is a substance called that speeds up a chemical reaction without being consumed?",
      a: "A catalyst." },
    { q: "What is the chemical symbol for sodium?",
      a: "Na (from the Latin 'natrium')." },
    { q: "How many electrons can the second electron shell of an atom hold?",
      a: "8 electrons (the 2s and 2p subshells together)." },
    { q: "What gas is typically produced when a reactive metal reacts with a dilute acid?",
      a: "Hydrogen gas (H₂)." },
    { q: "What is the common chemical name for nitrous oxide (N₂O)?",
      a: "Laughing gas." },
    { q: "What is the most common state of ordinary matter in the universe?",
      a: "Plasma, found in stars and interstellar gas." },
    { q: "What is the simplest hydrocarbon, with formula CH₄?",
      a: "Methane." },
    { q: "How many valence electrons does an oxygen atom have?",
      a: "6 valence electrons (oxygen is in group 16)." },
  ],

  chess: [
    { pieces: { g6: "wK", a1: "wQ", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qa8#. The queen slides to a8, attacking h8 along the 8th rank. The king's escape squares g7 and h7 are covered by the White king on g6, and g8 is covered by the queen on the 8th rank." },
    { pieces: { g6: "wK", b1: "wQ", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qb8#. Queen delivers check on the 8th rank; g7, h7 (White king) and g8 (queen) are all covered." },
    { pieces: { g6: "wK", c1: "wQ", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qc8#. Same 8th-rank pattern: White king covers g7 and h7, queen covers g8 and checks h8." },
    { pieces: { f7: "wK", d1: "wQ", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qd8#. Queen reaches d8, checking on the 8th rank; the White king on f7 covers g7, g8, and h7, so the black king has no flight square." },
    { pieces: { f7: "wK", e2: "wQ", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qh2#. The queen slides along the 2nd rank to h2, attacking down the h-file. The black king is in check and squares g7, g8 (White king) plus h7 (h-file) are all covered." },
    { pieces: { b6: "wK", h1: "wQ", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qh8#. The queen reaches h8 and checks along the 8th rank. The White king on b6 covers a7 and b7, and the queen covers b8 from h8." },
    { pieces: { b6: "wK", g2: "wQ", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qg8#. Eighth-rank mate: White king covers a7 and b7, queen on g8 covers b8 and gives check." },
    { pieces: { b6: "wK", d1: "wQ", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qd8#. Eighth-rank mate. The White king on b6 covers a7 and b7; the queen covers b8 and checks a8 along the 8th rank." },
    { pieces: { b6: "wK", c3: "wQ", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qc8#. Same pattern: 8th-rank check, b6 king covers the escape squares a7 and b7, queen covers b8." },
    { pieces: { b6: "wK", e5: "wQ", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qe8#. The queen lands on the 8th rank and checks a8; White king covers a7 and b7, the queen covers b8." },
    { pieces: { f2: "wK", a3: "wQ", h1: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qh3#. The queen reaches h3 and attacks down the h-file. The White king on f2 covers g1 and g2, and the queen covers h2." },
    { pieces: { f2: "wK", b4: "wQ", h1: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qh4#. h-file mate: White king covers g1 and g2; queen on h4 attacks h1 along the file." },
    { pieces: { g3: "wK", a2: "wQ", h1: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qh2#. The queen slides along the 2nd rank to h2, giving check on the h-file (and it is protected by the White king on g3). The squares g1 and g2 are covered by the queen on h2 and the White king." },
    { pieces: { c2: "wK", e4: "wQ", a1: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qa4#. The queen swings to a4 and checks along the a-file. The White king on c2 covers b1 and b2; the queen also covers a2 along the file." },
    { pieces: { b3: "wK", h5: "wQ", a1: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Qh1#. The queen reaches h1 and gives check along the 1st rank. The White king on b3 covers a2, b1 (along with the queen) and b2." },
    { pieces: { g6: "wK", a1: "wR", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Ra8#. Back-rank check: the White king on g6 covers g7 and h7, and the rook delivers mate from a8, covering g8 along the 8th rank." },
    { pieces: { g6: "wK", d1: "wR", h8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Rd8#. Same back-rank mate with the rook on a different file." },
    { pieces: { b6: "wK", h1: "wR", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Rh8#. The rook checks on the 8th rank; the White king covers a7 and b7 while the rook covers b8." },
    { pieces: { b6: "wK", f1: "wR", a8: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Rf8#. Eighth-rank mate: rook covers b8 and delivers check; the White king on b6 covers a7 and b7." },
    { pieces: { f2: "wK", a3: "wR", h1: "bK" },
      q: "White to move. Find the mate in one.",
      a: "Rh3#. The rook slides to h3 and attacks down the h-file. Black has no escape: g1 and g2 are covered by the White king, and h2 is attacked by the rook." },
  ],

  biology: [
    { q: "Who proposed the theory of evolution by natural selection?",
      a: "Charles Darwin (and independently Alfred Russel Wallace, 1858–1859)." },
    { q: "What landmark book did Darwin publish in 1859?",
      a: "On the Origin of Species (by Means of Natural Selection)." },
    { q: "How is biological evolution defined at the population level?",
      a: "As a change in the frequency of alleles (gene variants) in a population over generations." },
    { q: "Briefly, what is natural selection?",
      a: "The process by which heritable traits that increase survival and reproduction become more common in a population over time." },
    { q: "What is genetic drift?",
      a: "Random changes in allele frequencies from one generation to the next due to chance sampling; its effect is strongest in small populations." },
    { q: "Which island group, famous for its finches and tortoises, was a key source of Darwin's observations?",
      a: "The Galápagos Islands, visited during his voyage on HMS Beagle." },
    { q: "What term describes anatomical features inherited from a common ancestor that may have different functions today (e.g., the human arm and a whale's flipper)?",
      a: "Homologous structures." },
    { q: "What term describes features that look or function similarly but evolved independently (e.g., a bird's wing and an insect's wing)?",
      a: "Analogous structures, the result of convergent evolution." },
    { q: "What is the smallest biological unit that can undergo evolution?",
      a: "A population. Individuals do not evolve; allele frequencies change across a population over generations." },
    { q: "What is a vestigial structure? Give an example.",
      a: "A body part that has lost most or all of its original function over evolutionary time; examples include the human appendix, wisdom teeth, and the pelvic bones of whales." },
    { q: "What is the term for the process by which one species splits into two or more new species?",
      a: "Speciation." },
    { q: "What kind of speciation is caused by geographic isolation of populations?",
      a: "Allopatric speciation." },
    { q: "Name an organism often called a 'living fossil' because its lineage has remained morphologically similar for tens or hundreds of millions of years.",
      a: "Examples include the coelacanth, the horseshoe crab, the ginkgo tree, and the nautilus." },
    { q: "What molecule carries the genetic information passed from parents to offspring?",
      a: "DNA (deoxyribonucleic acid)." },
    { q: "When unrelated species independently evolve similar traits, what is this called?",
      a: "Convergent evolution (e.g., the wings of bats and birds, or echolocation in bats and dolphins)." },
    { q: "What is a mutation, and why does it matter for evolution?",
      a: "A change in the DNA sequence. Mutations are the ultimate source of new genetic variation on which natural selection acts." },
    { q: "Which pre-Darwinian scientist proposed (incorrectly) that traits acquired during an organism's lifetime are passed on to offspring?",
      a: "Jean-Baptiste Lamarck (Lamarckism, e.g., the idea that a giraffe stretches its neck and passes on a slightly longer neck)." },
    { q: "What is biodiversity?",
      a: "The variety of life in a given area, measured at the genetic, species, and ecosystem levels." },
    { q: "Name three independent lines of evidence supporting common ancestry of all life on Earth.",
      a: "Among many: a near-universal genetic code, shared core biochemistry (e.g., ATP, ribosomes), homologous anatomical structures, the fossil record showing transitional forms, and embryological similarities across vertebrates." },
    { q: "Approximately how old is the Earth, according to current scientific evidence?",
      a: "About 4.54 billion years, based on radiometric dating of meteorites and Earth's oldest rocks." },
  ],
};
